### ISSUE TITLE
Enabling the edit request button in user side

### ISSUE THREAD

**Issue by sainsaji** [sainsaji/Software_Access_Management#81]
Currently the edit request button does nothing, use it to edit remarks 
![image](https://github.com/sainsaji/Software_Access_Management/assets/95070425/8333f7ea-f5b9-460c-b814-0a76f4e1c5f8)

**Comment by Smith-Coder** [comment]
This issue was a duplicate

**Comment by Smith-Coder** [comment]
This issue was a duplicate and not planed
